[project]
name = "labelImg_refresh"
version = "1.9.3"
description = "Modernized LabelImg with YOLO auto-annotation"
authors = [{name = "SLY-F0X"}]
requires-python = ">=3.8"

dependencies = [
    "pyqt5",
    "lxml",
    "torch",
    "ultralytics",
    "pandas>=2.0.3",
]




